### ISSUE TITLE
Repair Review

### ISSUE THREAD

**Issue by ucalyptus** [IEM-Computer-Vision/ICCV19-Paper-Review#12]
[Link](https://iem-computer-vision.github.io/ICCV19-Paper-Review/Hierarchical%20Self-Attention%20Network)
@soumya997

**Comment by ucalyptus** [comment]
@soumya997 Author name is resolved. Just repair the blog

**Comment by Nibba2018** [comment]
was it fixed?

**Comment by soumya997** [comment]
@ucalyptus I have tried to repair the blog , so please check.....

**Comment by soumya997** [comment]
please check once again @ucalyptus
