### ISSUE TITLE
Tasks

### ISSUE THREAD

**Issue by ucalyptus** [IEM-Computer-Vision/ICCV19-Paper-Review#2]

**Comment by ucalyptus** [comment]
- DeepVCP: An End-to-End Deep Neural Network for Point Cloud Registration - @Nibba2018  :heavy_check_mark: 
- Shape Reconstruction Using Differentiable Projections and Deep Priors - @himanshuraj001 :heavy_check_mark: 
- Fine-Grained Segmentation Networks: Self-Supervised Segmentation for Improved Long-Term 
 Visual Localization - @SoumikNandi01 [Pending]

For links to the paper - Check Readme.md
Hope you all are well versed with markdown and making pull requests.

**Comment by ucalyptus** [comment]
Follow the video given in https://github.com/IEM-Computer-Vision/ICCV19-Paper-Review/pull/1 for some idea about pull requests.

**Comment by ucalyptus** [comment]
Markdown Cheatsheet Link here - https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet

**Comment by ucalyptus** [comment]
- SANet: Scene Agnostic Network for Camera Localization @Rajatava :heavy_check_mark: 
- Total Denoising: Unsupervised Learning of 3D Point Cloud Cleaning @shivishbrahma :heavy_check_mark: 
- Hierarchical Self-Attention Network for Action Localization in Videos @soumya997 :heavy_check_mark:

**Comment by ucalyptus** [comment]
- Goal-Driven Sequential Data Abstraction @Nibba2018 :heavy_check_mark:

**Comment by ucalyptus** [comment]
Great going @Nibba2018 . Here's another "Jointly Aligning Millions of Images With Deep Penalised Reconstruction Congealing" :heavy_check_mark:

**Comment by Nibba2018** [comment]
Thanks, will look into that ASAP 👍

**Comment by ucalyptus** [comment]
Drop to Adapt: Learning Discriminative Features for Unsupervised Domain Adaptation @shivishbrahma

**Comment by ucalyptus** [comment]
@shatadru99 In the Review Links use (www.iem-computer-vision.github.io/[INSERT PAPER NAME.md]) this format instead of github.com/iem- ......

**Comment by ucalyptus** [comment]
@soumya997 NLNL: Negative Learning for Noisy Labels :heavy_check_mark:

**Comment by ucalyptus** [comment]
@shatadru99 Paper : On the Design of Black-Box Adversarial Examples by Leveraging Gradient-Free Optimization and Operator Splitting Method

**Comment by ucalyptus** [comment]
@shivishbrahma @Nibba2018 @soumya997 @himanshuraj001 @shatadru99 @Rajatava Add your names to the newly created Review Author Column against the reviews you have completed.

**Comment by ucalyptus** [comment]
@SoumikNandi01 Check Github

**Comment by ucalyptus** [comment]
Closing this. All pending papers will be individually managed as separate papers.
