### ISSUE TITLE
Paper : On the Design of Black-Box Adversarial Examples by Leveraging Gradient-Free Optimization and Operator Splitting Method

### ISSUE THREAD

**Issue by ucalyptus** [IEM-Computer-Vision/ICCV19-Paper-Review#23]
@soumya997  Paper : On the Design of Black-Box Adversarial Examples by Leveraging Gradient-Free Optimization and Operator Splitting Method

**Comment by ucalyptus** [comment]
- When a PR is made. Mention the Entire URL of the issue it solves (in the comment thread of PR). There is an issue made by me for every assigned paper.
- Ensure picture links are working
- Ensure you mention all references, links to paper,code, etc
- Ensure you mention your name inside this file and also on the readme table .
- Github Pages is bad at rendering LaTeX (supposedly) so rather use images of math instead of notations. 
- Refer to my video in the group on how to make math formulae using [idroo](https://idroo.com/). 
- I understand it is painful to add math like this on a markdown file. Use idroo as much as possible and supplement idroo drawings with text explanations.

Ping me in the morning or afternoon of 17th Jan in the grp after changes are ensured. @soumya997

**Comment by ucalyptus** [comment]
If there isn't a problem can both of you work together for this issue?
Both of you shall be the authors then with equal contributions.
If this works out well, please collaborate .

**Comment by shatadru99** [comment]
DONE
