### ISSUE TITLE
Webpage Frontend needs improvement

### ISSUE THREAD

**Issue by ucalyptus** [IEM-Computer-Vision/ICCV19-Paper-Review#25]
- [x] Homepage 
- [x] An About Section 
- [x] Contact

**Comment by ucalyptus** [comment]
Use this space for website related discussion

**Comment by shivishbrahma** [comment]
Pages added to the main url and anything to edit just edit about and contact section @shivamdn9

**Comment by ucalyptus** [comment]
Thanks
