### ISSUE TITLE
GENERAL PR GUIDELINES

### ISSUE THREAD

**Issue by ucalyptus** [IEM-Computer-Vision/ICCV19-Paper-Review#47]
**Before you make a PR**
- Make sure links mentioned in your md especially those of images work properly.
- Check if md file is already there . In that case rather edit that file instead of uploading.
- Add your name to README against the review. It's useless without your name.
- Image Format 
 `<img src="./images/image-link-no-spaces.png" width="30" /> ` 
- Update your forked repo with the upstream . [Learn Here](https://www.youtube.com/watch?v=YhwBgYPfoVE)
- Create a new branch named `name-papername` in your fork. All changes should happen here and master should stay untouched. 
- Do not make changes in master.
- [Learn how to create pull requests](https://www.youtube.com/watch?v=8LRUpWrSj9A)
- Incase changes are requested on a PR, Close the pull request. Then make the changes in your PR and only then reopen the closed request. 
- In case you made some mistakes that do not have any solution, delete your fork and fork again. 
Make the above steps now. 
- Report me on the group chat if any of the links or pages in `https://iem-computer-vision.github.io/ICCV19-Paper-Review/` have an error in links.

**Comment by shivishbrahma** [comment]
For image links use `./images/<your_image_name.extension>`, never use absolute links, use relative links... Correcting @ucalyptus

**Comment by shivishbrahma** [comment]
By the way finally got a better way to solve with equations...
[Codecog Latex Editor](https://latex.codecogs.com/eqneditor/editor.php)
just type the equation in the editor in latex format
For Latex symbols visit [here](https://oeis.org/wiki/List_of_LaTeX_mathematical_symbols)
use \<img\> tag 
```
<img  class="eqn-inline" src="https://latex.codecogs.com/svg.latex?h(x;&space;m_f,&space;m_c)&space;=&space;c(f(x;&space;m_f);&space;m_c)">
```
Rendered equation is below
<img  class="eqn-inline" src="https://latex.codecogs.com/svg.latex?h(x;&space;m_f,&space;m_c)&space;=&space;c(f(x;&space;m_f);&space;m_c)">

for inline equation use class "eqn-inline" and for outline equations class "eqn-outline"

For help, you can take help from my paper [Drop to Adapt](https://github.com/IEM-Computer-Vision/ICCV19-Paper-Review/blob/master/Drop%20to%20Adapt.md)

@ucalyptus  @Nibba2018 @Palspal98 @himanshuraj001 @Rajatava @soumya997 @shatadru99 @shivamdn9

**Comment by Nibba2018** [comment]
* Filenames having special characters will lead to weird command-line errors, specifically `INVALID PATH` Error. For e.g this [filename](https://github.com/IEM-Computer-Vision/ICCV19-Paper-Review/commit/048f44d29e9ba57fac22676a828084a723dbabba) had a semicolon(:) and was interfering with git CLI, thus preventing me from updating my fork.

```bash
D:\Github\ICCV19-Paper-Review>git merge upstream/master
error: invalid path 'Fine-Grained Segmentation Networks: Self-Supervised Segmentation for Improved Long-Term Visual Localization.md'
Updating 9fd7491..048f44d

```

**Comment by ucalyptus** [comment]
>     * Filenames having special characters will lead to weird command-line errors, specifically `INVALID PATH` Error. For e.g this [filename](https://github.com/IEM-Computer-Vision/ICCV19-Paper-Review/commit/048f44d29e9ba57fac22676a828084a723dbabba) had a semicolon(:) and was interfering with git CLI, thus preventing me from updating my fork.
> 
> 
> ```shell
> D:\Github\ICCV19-Paper-Review>git merge upstream/master
> error: invalid path 'Fine-Grained Segmentation Networks: Self-Supervised Segmentation for Improved Long-Term Visual Localization.md'
> Updating 9fd7491..048f44d
> ```

This we have to make sure that we do not copy the colon or semicolon while creating the filename
